controllers:
    prefix: /{_locale}
    resource: ../../src/Controller/
    type: annotation
    requirements: 
        _locale: fr|en



kernel:
    resource: ../../src/Kernel.php
    type: annotation